# Generated by Django 3.1.3 on 2020-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stem_app', '0002_auto_20201118_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavereport',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
