# Generated by Django 3.1.3 on 2020-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_stem_app', '0005_auto_20201123_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
