# Generated by Django 3.1.3 on 2020-11-30 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_stem_app', '0006_auto_20201129_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fcm_token',
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_exam', models.FloatField(default=0)),
                ('subject_assignment', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_stem_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_stem_app.subjects')),
            ],
        ),
    ]
